name: CI Build & Publish
on:
push:
branches: [ main ]
workflow_dispatch:


jobs:
build-and-push:
runs-on: ubuntu-latest
permissions:
contents: read
packages: write
id-token: write


steps:
- uses: actions/checkout@v4


- name: Log in to GitHub Container Registry
uses: docker/login-action@v2
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GHCR_TOKEN }}


- name: Set up QEMU
uses: docker/setup-qemu-action@v2


- name: Set up Docker Buildx
uses: docker/setup-buildx-action@v2


- name: Build and push node-proxy
uses: docker/build-push-action@v4
with:
context: ./services/node-proxy
push: true
tags: ghcr.io/${{ github.repository_owner }}/interstellar-node-proxy:latest


- name: Build and push python-cache
uses: docker/build-push-action@v4
with:
context: ./services/python-cache
push: true
tags: ghcr.io/${{ github.repository_owner }}/interstellar-python-cache:latest


- name: Build and push java-rate
uses: docker/build-push-action@v4
with:
context: ./services/java-rate
push: true
tags: ghcr.io/${{ github.repository_owner }}/interstellar-java-rate:latest


# add other services similarly


- name: Logout
run: docker logout ghcr.io
